name: Dynare 5.4 with MATLAB R2023a

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  dynare_5_4_matlab_r2023a:
    uses: ./.github/workflows/dynare-matlab-common.yml
    with:
      dynare-version: "5.4"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}