name: Dynare 4.6.4 with MATLAB R2021a

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  dynare_4_6_4_matlab_r2021a:
    uses: ./.github/workflows/dynare-matlab-common.yml
    with:
      dynare-version: "4.6.4"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}